name: smiple_media_player
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  desktop_drop: ^0.7.0
  file_picker: ^10.3.6
  flutter:
    sdk: flutter
  flutter_media_metadata: ^1.0.0+1
  go_router: ^17.0.0
  hooks_riverpod: ^3.0.3
  lucide_icons_flutter: ^3.1.6
  media_kit: ^1.2.2
  media_source: ^1.0.0
  path: ^1.9.1
  riverpod: ^3.0.3
  video_player: ^2.10.1
  window_manager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
